// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated Dart FFI bindings for baresdk.
class BareSDKBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BareSDKBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BareSDKBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Char> baresdk_version() {
    return _baresdk_version();
  }

  late final _baresdk_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'baresdk_version');
  late final _baresdk_version =
      _baresdk_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Zero-fill cfg and set version/struct_size correctly. Call before populating.
  void baresdk_config_init(
    ffi.Pointer<baresdk_config_t> cfg,
  ) {
    return _baresdk_config_init(
      cfg,
    );
  }

  late final _baresdk_config_initPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<baresdk_config_t>)>>(
      'baresdk_config_init');
  late final _baresdk_config_init = _baresdk_config_initPtr
      .asFunction<void Function(ffi.Pointer<baresdk_config_t>)>();

  /// Initialize the baresdk stack. Call once per process before any other API.
  /// Spawns re_main thread and event dispatch thread internally.
  /// Returns BARESDK_OK or a negative BARESDK_ERR_* code.
  int baresdk_init(
    ffi.Pointer<baresdk_config_t> cfg,
  ) {
    return _baresdk_init(
      cfg,
    );
  }

  late final _baresdk_initPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<baresdk_config_t>)>>(
      'baresdk_init');
  late final _baresdk_init = _baresdk_initPtr
      .asFunction<int Function(ffi.Pointer<baresdk_config_t>)>();

  /// Tear down the stack. Blocks until all internal threads have exited.
  /// All active accounts and calls are forcibly terminated first.
  void baresdk_shutdown() {
    return _baresdk_shutdown();
  }

  late final _baresdk_shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('baresdk_shutdown');
  late final _baresdk_shutdown =
      _baresdk_shutdownPtr.asFunction<void Function()>();

  /// Create a SIP account. Does NOT register — call baresdk_account_register().
  /// Thread-safe; may be called from any thread after baresdk_init().
  int baresdk_account_create(
    ffi.Pointer<baresdk_account_config_t> cfg,
    ffi.Pointer<baresdk_account_handle_t> out,
  ) {
    return _baresdk_account_create(
      cfg,
      out,
    );
  }

  late final _baresdk_account_createPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(ffi.Pointer<baresdk_account_config_t>,
                  ffi.Pointer<baresdk_account_handle_t>)>>(
      'baresdk_account_create');
  late final _baresdk_account_create = _baresdk_account_createPtr.asFunction<
      int Function(ffi.Pointer<baresdk_account_config_t>,
          ffi.Pointer<baresdk_account_handle_t>)>();

  /// Destroy account and all associated calls. Unregisters first if registered.
  void baresdk_account_destroy(
    baresdk_account_handle_t acct,
  ) {
    return _baresdk_account_destroy(
      acct,
    );
  }

  late final _baresdk_account_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(baresdk_account_handle_t)>>(
          'baresdk_account_destroy');
  late final _baresdk_account_destroy = _baresdk_account_destroyPtr
      .asFunction<void Function(baresdk_account_handle_t)>();

  /// Begin registration. Fires BARESDK_EV_REG_STATE events on state changes.
  int baresdk_account_register(
    baresdk_account_handle_t acct,
  ) {
    return _baresdk_account_register(
      acct,
    );
  }

  late final _baresdk_account_registerPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_account_handle_t)>>(
          'baresdk_account_register');
  late final _baresdk_account_register = _baresdk_account_registerPtr
      .asFunction<int Function(baresdk_account_handle_t)>();

  /// Unregister (sends REGISTER with Expires: 0).
  int baresdk_account_unregister(
    baresdk_account_handle_t acct,
  ) {
    return _baresdk_account_unregister(
      acct,
    );
  }

  late final _baresdk_account_unregisterPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_account_handle_t)>>(
          'baresdk_account_unregister');
  late final _baresdk_account_unregister = _baresdk_account_unregisterPtr
      .asFunction<int Function(baresdk_account_handle_t)>();

  /// Override the retry policy for this account. Takes effect on the next retry.
  /// Overrides the global reg_retry_* fields in baresdk_config_t for this account only.
  /// @param initial_ms   First retry delay in ms (e.g. 2000)
  /// @param max_ms       Maximum retry delay cap in ms (e.g. 300000)
  /// @param backoff      Delay multiplier per attempt (e.g. 2.0)
  /// @param max_attempts Max attempts before giving up; 0 = retry forever
  int baresdk_account_set_retry_policy(
    baresdk_account_handle_t acct,
    int initial_ms,
    int max_ms,
    double backoff,
    int max_attempts,
  ) {
    return _baresdk_account_set_retry_policy(
      acct,
      initial_ms,
      max_ms,
      backoff,
      max_attempts,
    );
  }

  late final _baresdk_account_set_retry_policyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t, ffi.Uint32, ffi.Uint32,
              ffi.Float, ffi.Uint32)>>('baresdk_account_set_retry_policy');
  late final _baresdk_account_set_retry_policy =
      _baresdk_account_set_retry_policyPtr.asFunction<
          int Function(baresdk_account_handle_t, int, int, double, int)>();

  /// Cancel a pending retry timer and reset the attempt counter.
  /// The account stays in FAILED state; call baresdk_account_register() to restart.
  int baresdk_account_cancel_retry(
    baresdk_account_handle_t acct,
  ) {
    return _baresdk_account_cancel_retry(
      acct,
    );
  }

  late final _baresdk_account_cancel_retryPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_account_handle_t)>>(
          'baresdk_account_cancel_retry');
  late final _baresdk_account_cancel_retry = _baresdk_account_cancel_retryPtr
      .asFunction<int Function(baresdk_account_handle_t)>();

  /// Skip the current backoff delay and re-register immediately.
  /// Resets the attempt counter. No-op if the account is not in a retry loop.
  int baresdk_account_retry_now(
    baresdk_account_handle_t acct,
  ) {
    return _baresdk_account_retry_now(
      acct,
    );
  }

  late final _baresdk_account_retry_nowPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_account_handle_t)>>(
          'baresdk_account_retry_now');
  late final _baresdk_account_retry_now = _baresdk_account_retry_nowPtr
      .asFunction<int Function(baresdk_account_handle_t)>();

  /// Add a custom SIP header to all outgoing requests for this account.
  /// @param name   Header field name  (e.g. "X-Tenant-Id")
  /// @param value  Header field value (e.g. "12345")
  int baresdk_account_add_header(
    baresdk_account_handle_t acct,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _baresdk_account_add_header(
      acct,
      name,
      value,
    );
  }

  late final _baresdk_account_add_headerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('baresdk_account_add_header');
  late final _baresdk_account_add_header =
      _baresdk_account_add_headerPtr.asFunction<
          int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>();

  /// Subscribe to presence state changes for a contact (SUBSCRIBE/NOTIFY).
  /// Presence updates are delivered via BARESDK_EV_PRESENCE_STATE events.
  /// @param target_uri  SIP URI of the contact to subscribe to
  /// @return BARESDK_OK on success, or negative error code
  int baresdk_account_subscribe_presence(
    baresdk_account_handle_t acct,
    ffi.Pointer<ffi.Char> target_uri,
  ) {
    return _baresdk_account_subscribe_presence(
      acct,
      target_uri,
    );
  }

  late final _baresdk_account_subscribe_presencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t,
              ffi.Pointer<ffi.Char>)>>('baresdk_account_subscribe_presence');
  late final _baresdk_account_subscribe_presence =
      _baresdk_account_subscribe_presencePtr.asFunction<
          int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>)>();

  /// Unsubscribe from presence state changes for a contact.
  /// @param target_uri  SIP URI of the contact to unsubscribe from
  /// @return BARESDK_OK on success, or negative error code
  int baresdk_account_unsubscribe_presence(
    baresdk_account_handle_t acct,
    ffi.Pointer<ffi.Char> target_uri,
  ) {
    return _baresdk_account_unsubscribe_presence(
      acct,
      target_uri,
    );
  }

  late final _baresdk_account_unsubscribe_presencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t,
              ffi.Pointer<ffi.Char>)>>('baresdk_account_unsubscribe_presence');
  late final _baresdk_account_unsubscribe_presence =
      _baresdk_account_unsubscribe_presencePtr.asFunction<
          int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>)>();

  /// Initiate an outgoing call. Returns immediately; fires BARESDK_EV_CALL_STATE
  /// CALLING, then RINGING, then ESTABLISHED (or FAILED).
  int baresdk_call_invite(
    baresdk_account_handle_t acct,
    ffi.Pointer<ffi.Char> uri,
    ffi.Pointer<baresdk_call_handle_t> out,
  ) {
    return _baresdk_call_invite(
      acct,
      uri,
      out,
    );
  }

  late final _baresdk_call_invitePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>,
              ffi.Pointer<baresdk_call_handle_t>)>>('baresdk_call_invite');
  late final _baresdk_call_invite = _baresdk_call_invitePtr.asFunction<
      int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>,
          ffi.Pointer<baresdk_call_handle_t>)>();

  /// Answer an incoming call (received via BARESDK_EV_INCOMING_CALL).
  int baresdk_call_answer(
    baresdk_call_handle_t call,
  ) {
    return _baresdk_call_answer(
      call,
    );
  }

  late final _baresdk_call_answerPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_call_handle_t)>>(
          'baresdk_call_answer');
  late final _baresdk_call_answer =
      _baresdk_call_answerPtr.asFunction<int Function(baresdk_call_handle_t)>();

  /// Terminate a call with BYE.
  int baresdk_call_hangup(
    baresdk_call_handle_t call,
  ) {
    return _baresdk_call_hangup(
      call,
    );
  }

  late final _baresdk_call_hangupPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_call_handle_t)>>(
          'baresdk_call_hangup');
  late final _baresdk_call_hangup =
      _baresdk_call_hangupPtr.asFunction<int Function(baresdk_call_handle_t)>();

  /// Put call on hold (re-INVITE with sendonly).
  int baresdk_call_hold(
    baresdk_call_handle_t call,
  ) {
    return _baresdk_call_hold(
      call,
    );
  }

  late final _baresdk_call_holdPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_call_handle_t)>>(
          'baresdk_call_hold');
  late final _baresdk_call_hold =
      _baresdk_call_holdPtr.asFunction<int Function(baresdk_call_handle_t)>();

  /// Resume a held call (re-INVITE with sendrecv).
  int baresdk_call_resume(
    baresdk_call_handle_t call,
  ) {
    return _baresdk_call_resume(
      call,
    );
  }

  late final _baresdk_call_resumePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_call_handle_t)>>(
          'baresdk_call_resume');
  late final _baresdk_call_resume =
      _baresdk_call_resumePtr.asFunction<int Function(baresdk_call_handle_t)>();

  /// Send DTMF digit via RFC 4733 RTP events. digit: '0'-'9', '*', '#', 'A'-'D'.
  int baresdk_call_send_dtmf(
    baresdk_call_handle_t call,
    int digit,
  ) {
    return _baresdk_call_send_dtmf(
      call,
      digit,
    );
  }

  late final _baresdk_call_send_dtmfPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(baresdk_call_handle_t, ffi.Char)>>(
      'baresdk_call_send_dtmf');
  late final _baresdk_call_send_dtmf = _baresdk_call_send_dtmfPtr
      .asFunction<int Function(baresdk_call_handle_t, int)>();

  /// Blind transfer via REFER.
  int baresdk_call_transfer(
    baresdk_call_handle_t call,
    ffi.Pointer<ffi.Char> uri,
  ) {
    return _baresdk_call_transfer(
      call,
      uri,
    );
  }

  late final _baresdk_call_transferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_call_handle_t,
              ffi.Pointer<ffi.Char>)>>('baresdk_call_transfer');
  late final _baresdk_call_transfer = _baresdk_call_transferPtr
      .asFunction<int Function(baresdk_call_handle_t, ffi.Pointer<ffi.Char>)>();

  /// Add a custom SIP header to a specific call/dialog.
  /// Headers are applied to subsequent re-INVITEs, BYE, and REFER messages
  /// within this dialog. Must be called while the call is active.
  /// @param name   Header field name  (e.g. "X-Call-Id")
  /// @param value  Header field value (e.g. "12345")
  int baresdk_call_add_header(
    baresdk_call_handle_t call,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _baresdk_call_add_header(
      call,
      name,
      value,
    );
  }

  late final _baresdk_call_add_headerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_call_handle_t, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('baresdk_call_add_header');
  late final _baresdk_call_add_header = _baresdk_call_add_headerPtr.asFunction<
      int Function(baresdk_call_handle_t, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>)>();

  /// Attended transfer: send REFER w/ Replaces on call_a, bridging it to call_b.
  /// call_a is the call to transfer away; call_b is the already-established
  /// consultation call whose dialog info is embedded in Replaces.
  int baresdk_call_attended_transfer(
    baresdk_call_handle_t call_a,
    baresdk_call_handle_t call_b,
  ) {
    return _baresdk_call_attended_transfer(
      call_a,
      call_b,
    );
  }

  late final _baresdk_call_attended_transferPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_call_handle_t,
              baresdk_call_handle_t)>>('baresdk_call_attended_transfer');
  late final _baresdk_call_attended_transfer =
      _baresdk_call_attended_transferPtr.asFunction<
          int Function(baresdk_call_handle_t, baresdk_call_handle_t)>();

  /// Send a SIP MESSAGE (instant message) out of dialog.
  /// content_type defaults to "text/plain" if NULL.
  /// Fires BARESDK_EV_MESSAGE on the remote end when received.
  int baresdk_message_send(
    baresdk_account_handle_t account,
    ffi.Pointer<ffi.Char> to_uri,
    ffi.Pointer<ffi.Char> body,
    ffi.Pointer<ffi.Char> content_type,
  ) {
    return _baresdk_message_send(
      account,
      to_uri,
      body,
      content_type,
    );
  }

  late final _baresdk_message_sendPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              baresdk_account_handle_t,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('baresdk_message_send');
  late final _baresdk_message_send = _baresdk_message_sendPtr.asFunction<
      int Function(baresdk_account_handle_t, ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();

  /// Publish presence status for the account (PUBLISH request).
  /// Fires BARESDK_EV_PRESENCE_STATE on subscribed watchers.
  int baresdk_account_publish_presence(
    baresdk_account_handle_t account,
    int status,
  ) {
    return _baresdk_account_publish_presence(
      account,
      status,
    );
  }

  late final _baresdk_account_publish_presencePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t,
              ffi.Int32)>>('baresdk_account_publish_presence');
  late final _baresdk_account_publish_presence =
      _baresdk_account_publish_presencePtr
          .asFunction<int Function(baresdk_account_handle_t, int)>();

  /// Set the RFC 3262 100rel mode for an account.
  /// Must be called before baresdk_call_invite / baresdk_call_answer.
  int baresdk_account_set_100rel(
    baresdk_account_handle_t account,
    int mode,
  ) {
    return _baresdk_account_set_100rel(
      account,
      mode,
    );
  }

  late final _baresdk_account_set_100relPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_account_handle_t,
              ffi.Int32)>>('baresdk_account_set_100rel');
  late final _baresdk_account_set_100rel = _baresdk_account_set_100relPtr
      .asFunction<int Function(baresdk_account_handle_t, int)>();

  /// Fill devices[] with available audio input devices, up to max_count entries.
  /// Returns the number of entries written (0 if no devices found yet).
  /// Call after baresdk_init(); device lists may be empty until the audio
  /// module has finished async enumeration.
  int baresdk_audio_list_input_devices(
    ffi.Pointer<baresdk_audio_device_t> devices,
    int max_count,
  ) {
    return _baresdk_audio_list_input_devices(
      devices,
      max_count,
    );
  }

  late final _baresdk_audio_list_input_devicesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<baresdk_audio_device_t>,
              ffi.Int)>>('baresdk_audio_list_input_devices');
  late final _baresdk_audio_list_input_devices =
      _baresdk_audio_list_input_devicesPtr
          .asFunction<int Function(ffi.Pointer<baresdk_audio_device_t>, int)>();

  /// Same for audio output (speaker/playback) devices.
  int baresdk_audio_list_output_devices(
    ffi.Pointer<baresdk_audio_device_t> devices,
    int max_count,
  ) {
    return _baresdk_audio_list_output_devices(
      devices,
      max_count,
    );
  }

  late final _baresdk_audio_list_output_devicesPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<baresdk_audio_device_t>,
              ffi.Int)>>('baresdk_audio_list_output_devices');
  late final _baresdk_audio_list_output_devices =
      _baresdk_audio_list_output_devicesPtr
          .asFunction<int Function(ffi.Pointer<baresdk_audio_device_t>, int)>();

  /// Enable/disable acoustic echo suppression globally (takes effect next frame).
  void baresdk_set_aec(
    bool enable,
  ) {
    return _baresdk_set_aec(
      enable,
    );
  }

  late final _baresdk_set_aecPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'baresdk_set_aec');
  late final _baresdk_set_aec =
      _baresdk_set_aecPtr.asFunction<void Function(bool)>();

  /// Enable/disable noise suppression globally (takes effect next frame).
  void baresdk_set_ns(
    bool enable,
  ) {
    return _baresdk_set_ns(
      enable,
    );
  }

  late final _baresdk_set_nsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'baresdk_set_ns');
  late final _baresdk_set_ns =
      _baresdk_set_nsPtr.asFunction<void Function(bool)>();

  /// Enable/disable automatic gain control globally (takes effect next frame).
  void baresdk_set_agc(
    bool enable,
  ) {
    return _baresdk_set_agc(
      enable,
    );
  }

  late final _baresdk_set_agcPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Bool)>>(
          'baresdk_set_agc');
  late final _baresdk_set_agc =
      _baresdk_set_agcPtr.asFunction<void Function(bool)>();

  /// Change DSCP/TOS on the RTP socket of an active call.
  /// Common values: 46 (EF — voice), 34 (AF41 — video), 0 (best-effort).
  /// Takes effect immediately on the next outgoing RTP packet.
  int baresdk_call_set_dscp_rtp(
    baresdk_call_handle_t call,
    int dscp,
  ) {
    return _baresdk_call_set_dscp_rtp(
      call,
      dscp,
    );
  }

  late final _baresdk_call_set_dscp_rtpPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(baresdk_call_handle_t, ffi.Uint8)>>(
      'baresdk_call_set_dscp_rtp');
  late final _baresdk_call_set_dscp_rtp = _baresdk_call_set_dscp_rtpPtr
      .asFunction<int Function(baresdk_call_handle_t, int)>();

  /// Update jitter buffer bounds.  Takes effect on calls established after
  /// this call — existing streams keep their current adaptive depth.
  /// Pass 0 for either bound to restore the baresip default (~0 / 150 ms).
  void baresdk_set_jitter_buffer(
    int min_ms,
    int max_ms,
  ) {
    return _baresdk_set_jitter_buffer(
      min_ms,
      max_ms,
    );
  }

  late final _baresdk_set_jitter_bufferPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint32, ffi.Uint32)>>(
          'baresdk_set_jitter_buffer');
  late final _baresdk_set_jitter_buffer =
      _baresdk_set_jitter_bufferPtr.asFunction<void Function(int, int)>();

  /// Mute/unmute the microphone (TX path) for a call.
  int baresdk_audio_mute(
    baresdk_call_handle_t call,
    bool mute,
  ) {
    return _baresdk_audio_mute(
      call,
      mute,
    );
  }

  late final _baresdk_audio_mutePtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(baresdk_call_handle_t, ffi.Bool)>>(
      'baresdk_audio_mute');
  late final _baresdk_audio_mute = _baresdk_audio_mutePtr
      .asFunction<int Function(baresdk_call_handle_t, bool)>();

  /// Mute/unmute the speaker (RX path) for a call — silences incoming audio.
  int baresdk_audio_mute_rx(
    baresdk_call_handle_t call,
    bool mute,
  ) {
    return _baresdk_audio_mute_rx(
      call,
      mute,
    );
  }

  late final _baresdk_audio_mute_rxPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(baresdk_call_handle_t, ffi.Bool)>>(
      'baresdk_audio_mute_rx');
  late final _baresdk_audio_mute_rx = _baresdk_audio_mute_rxPtr
      .asFunction<int Function(baresdk_call_handle_t, bool)>();

  /// Set the system audio input device by name. NULL = platform default.
  int baresdk_audio_set_input_device(
    ffi.Pointer<ffi.Char> name,
  ) {
    return _baresdk_audio_set_input_device(
      name,
    );
  }

  late final _baresdk_audio_set_input_devicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'baresdk_audio_set_input_device');
  late final _baresdk_audio_set_input_device =
      _baresdk_audio_set_input_devicePtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Set the system audio output device by name. NULL = platform default.
  int baresdk_audio_set_output_device(
    ffi.Pointer<ffi.Char> name,
  ) {
    return _baresdk_audio_set_output_device(
      name,
    );
  }

  late final _baresdk_audio_set_output_devicePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'baresdk_audio_set_output_device');
  late final _baresdk_audio_set_output_device =
      _baresdk_audio_set_output_devicePtr
          .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Install a PCM tap on an active call.
  /// cb is called from the audio thread for both RX (decoded) and TX (pre-encode)
  /// directions. Must be non-blocking — heavy work must go to your own thread.
  /// Pass NULL cb to remove the tap.
  int baresdk_call_set_media_tap(
    baresdk_call_handle_t call,
    baresdk_media_tap_cb_t cb,
    ffi.Pointer<ffi.Void> userdata,
  ) {
    return _baresdk_call_set_media_tap(
      call,
      cb,
      userdata,
    );
  }

  late final _baresdk_call_set_media_tapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_call_handle_t, baresdk_media_tap_cb_t,
              ffi.Pointer<ffi.Void>)>>('baresdk_call_set_media_tap');
  late final _baresdk_call_set_media_tap =
      _baresdk_call_set_media_tapPtr.asFunction<
          int Function(baresdk_call_handle_t, baresdk_media_tap_cb_t,
              ffi.Pointer<ffi.Void>)>();

  /// Start recording call audio to a single mixed WAV file (PCM S16LE).
  /// Both the received (RX) and sent (TX) audio are clip-summed into one stream.
  /// The WAV header is written on the first audio frame and finalized on stop.
  /// Returns EALREADY if recording is already active.
  int baresdk_call_record_start(
    baresdk_call_handle_t call,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _baresdk_call_record_start(
      call,
      path,
    );
  }

  late final _baresdk_call_record_startPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(baresdk_call_handle_t,
              ffi.Pointer<ffi.Char>)>>('baresdk_call_record_start');
  late final _baresdk_call_record_start = _baresdk_call_record_startPtr
      .asFunction<int Function(baresdk_call_handle_t, ffi.Pointer<ffi.Char>)>();

  /// Stop recording and finalize WAV headers. Idempotent.
  int baresdk_call_record_stop(
    baresdk_call_handle_t call,
  ) {
    return _baresdk_call_record_stop(
      call,
    );
  }

  late final _baresdk_call_record_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(baresdk_call_handle_t)>>(
          'baresdk_call_record_stop');
  late final _baresdk_call_record_stop = _baresdk_call_record_stopPtr
      .asFunction<int Function(baresdk_call_handle_t)>();

  /// Synchronously retrieve current stats for a call.
  /// Also delivered automatically via BARESDK_EV_MEDIA_STATS if
  /// cfg.stats_interval_ms > 0.
  int baresdk_call_get_stats(
    baresdk_call_handle_t call,
    ffi.Pointer<baresdk_ev_media_stats_t> out,
  ) {
    return _baresdk_call_get_stats(
      call,
      out,
    );
  }

  late final _baresdk_call_get_statsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int Function(baresdk_call_handle_t,
                  ffi.Pointer<baresdk_ev_media_stats_t>)>>(
      'baresdk_call_get_stats');
  late final _baresdk_call_get_stats = _baresdk_call_get_statsPtr.asFunction<
      int Function(
          baresdk_call_handle_t, ffi.Pointer<baresdk_ev_media_stats_t>)>();

  /// Start capturing SIP + RTP to a Wireshark-compatible pcap file.
  /// Writes synthetic Ethernet/IP/UDP headers around each SIP message.
  int baresdk_pcap_start(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _baresdk_pcap_start(
      path,
    );
  }

  late final _baresdk_pcap_startPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
          'baresdk_pcap_start');
  late final _baresdk_pcap_start =
      _baresdk_pcap_startPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Stop capture and flush/close the pcap file.
  int baresdk_pcap_stop() {
    return _baresdk_pcap_stop();
  }

  late final _baresdk_pcap_stopPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('baresdk_pcap_stop');
  late final _baresdk_pcap_stop =
      _baresdk_pcap_stopPtr.asFunction<int Function()>();
}

final class baresdk_account extends ffi.Opaque {}

final class baresdk_call extends ffi.Opaque {}

/// ── Enumerations ───────────────────────────────────────────────────────────
abstract class baresdk_transport_t {
  static const int BARESDK_TRANSPORT_UDP = 0;
  static const int BARESDK_TRANSPORT_TCP = 1;
  static const int BARESDK_TRANSPORT_TLS = 2;
  static const int BARESDK_TRANSPORT_WS = 3;
  static const int BARESDK_TRANSPORT_WSS = 4;
}

abstract class baresdk_media_enc_t {
  static const int BARESDK_MEDIA_ENC_NONE = 0;
  static const int BARESDK_MEDIA_ENC_SDES = 1;
  static const int BARESDK_MEDIA_ENC_DTLS_SRTP = 2;
}

abstract class baresdk_codec_t {
  static const int BARESDK_CODEC_OPUS = 0;

  /// G.711 µ-law
  static const int BARESDK_CODEC_PCMU = 1;

  /// G.711 A-law
  static const int BARESDK_CODEC_PCMA = 2;
  static const int BARESDK_CODEC_G722 = 3;
}

abstract class baresdk_mos_method_t {
  static const int BARESDK_MOS_EMODEL = 0;
  static const int BARESDK_MOS_SIMPLIFIED = 1;
}

abstract class baresdk_media_dir_t {
  static const int BARESDK_MEDIA_DIR_RX = 0;
  static const int BARESDK_MEDIA_DIR_TX = 1;
}

/// ── Error codes ────────────────────────────────────────────────────────────
abstract class baresdk_error_t {
  static const int BARESDK_OK = 0;
  static const int BARESDK_ERR_INVAL = -1;
  static const int BARESDK_ERR_NOMEM = -2;

  /// wrong lifecycle state
  static const int BARESDK_ERR_STATE = -3;
  static const int BARESDK_ERR_DNS = -4;
  static const int BARESDK_ERR_TRANSPORT = -5;
  static const int BARESDK_ERR_AUTH = -6;
  static const int BARESDK_ERR_SERVER_5XX = -7;
  static const int BARESDK_ERR_WS_PROTOCOL_REJECTED = -8;
  static const int BARESDK_ERR_TIMEOUT = -9;
  static const int BARESDK_ERR_ALREADY = -10;
}

/// ── Call states ────────────────────────────────────────────────────────────
abstract class baresdk_call_state_t {
  static const int BARESDK_CALL_CALLING = 0;
  static const int BARESDK_CALL_RINGING = 1;
  static const int BARESDK_CALL_ESTABLISHED = 2;
  static const int BARESDK_CALL_HELD = 3;
  static const int BARESDK_CALL_ENDED = 4;
  static const int BARESDK_CALL_CANCELLED = 5;
  static const int BARESDK_CALL_FAILED = 6;
}

/// ── Registration states ────────────────────────────────────────────────────
abstract class baresdk_reg_state_t {
  static const int BARESDK_REG_UNREGISTERED = 0;
  static const int BARESDK_REG_REGISTERING = 1;
  static const int BARESDK_REG_REGISTERED = 2;
  static const int BARESDK_REG_FAILED = 3;
  static const int BARESDK_REG_UNREGISTERING = 4;
}

/// ── Presence enums ──────────────────────────────────────────────────────────
abstract class baresdk_presence_status_t {
  static const int BARESDK_PRESENCE_UNKNOWN = 0;

  /// available
  static const int BARESDK_PRESENCE_OPEN = 1;

  /// offline / DND
  static const int BARESDK_PRESENCE_CLOSED = 2;

  /// on a call
  static const int BARESDK_PRESENCE_BUSY = 3;
}

abstract class baresdk_100rel_mode_t {
  /// never send/require 100rel
  static const int BARESDK_100REL_DISABLED = 0;

  /// support 100rel if peer offers
  static const int BARESDK_100REL_ENABLED = 1;

  /// require 100rel; reject if unsupported
  static const int BARESDK_100REL_REQUIRED = 2;
}

/// ── Event types ────────────────────────────────────────────────────────────
abstract class baresdk_event_type_t {
  static const int BARESDK_EV_LOG = 0;
  static const int BARESDK_EV_REG_STATE = 1;
  static const int BARESDK_EV_INCOMING_CALL = 2;
  static const int BARESDK_EV_CALL_STATE = 3;
  static const int BARESDK_EV_CALL_DTMF = 4;
  static const int BARESDK_EV_SDP_NEGOTIATION = 5;
  static const int BARESDK_EV_SIP_TRACE = 6;
  static const int BARESDK_EV_MEDIA_STATS = 7;
  static const int BARESDK_EV_REGISTRAR_WARNING = 8;
  static const int BARESDK_EV_TRANSFER_REQUEST = 9;
  static const int BARESDK_EV_MWI = 10;
  static const int BARESDK_EV_MESSAGE = 11;
  static const int BARESDK_EV_PRESENCE_STATE = 12;
}

/// ── Event payload structs ──────────────────────────────────────────────────
final class baresdk_ev_reg_state_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  @ffi.Int32()
  external int state;

  /// BARESDK_OK when REGISTERED
  @ffi.Int32()
  external int error;

  @ffi.Uint32()
  external int retry_attempt;

  @ffi.Uint32()
  external int retry_delay_ms;

  /// human-readable; NULL on OK
  external ffi.Pointer<ffi.Char> error_str;
}

/// ── Opaque handles ─────────────────────────────────────────────────────────
typedef baresdk_account_handle_t = ffi.Pointer<baresdk_account>;

final class baresdk_ev_incoming_call_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  external baresdk_call_handle_t call;

  external ffi.Pointer<ffi.Char> from_uri;

  external ffi.Pointer<ffi.Char> display_name;
}

typedef baresdk_call_handle_t = ffi.Pointer<baresdk_call>;

final class baresdk_ev_call_state_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  external baresdk_call_handle_t call;

  @ffi.Int32()
  external int state;

  @ffi.Int32()
  external int error;

  external ffi.Pointer<ffi.Char> reason;
}

final class baresdk_ev_call_dtmf_t extends ffi.Struct {
  external baresdk_call_handle_t call;

  @ffi.Char()
  external int digit;
}

final class baresdk_ev_sdp_negotiation_t extends ffi.Struct {
  external baresdk_call_handle_t call;

  external ffi.Pointer<ffi.Char> local_sdp;

  external ffi.Pointer<ffi.Char> remote_sdp;

  external ffi.Pointer<ffi.Char> negotiated_codec;

  /// "NONE", "SDES", "DTLS-SRTP"
  external ffi.Pointer<ffi.Char> negotiated_crypto;

  /// NULL-terminated array
  external ffi.Pointer<ffi.Pointer<ffi.Char>> rejected_codecs;

  /// NULL-terminated array
  external ffi.Pointer<ffi.Pointer<ffi.Char>> warnings;
}

final class baresdk_ev_sip_trace_t extends ffi.Struct {
  @ffi.Int32()
  external int dir;

  /// "UDP", "TCP", "TLS", "WS", "WSS"
  external ffi.Pointer<ffi.Char> transport;

  /// "1.2.3.4:5060"
  external ffi.Pointer<ffi.Char> remote_addr;

  external ffi.Pointer<ffi.Char> raw_message;

  @ffi.Uint64()
  external int timestamp_us;
}

final class baresdk_ev_media_stats_t extends ffi.Struct {
  external baresdk_call_handle_t call;

  /// ── Packet counters ─────────────────────────────────────────────────
  @ffi.Uint32()
  external int packets_sent;

  @ffi.Uint32()
  external int packets_received;

  /// TX-side: packets remote did not receive
  @ffi.Uint32()
  external int packets_lost;

  /// RX-side: packets we did not receive
  @ffi.Uint32()
  external int packets_lost_rx;

  /// total RTP bytes sent
  @ffi.Uint32()
  external int bytes_sent;

  /// total RTP bytes received
  @ffi.Uint32()
  external int bytes_received;

  /// RTP transmit errors
  @ffi.Uint32()
  external int tx_errors;

  /// RTP receive errors
  @ffi.Uint32()
  external int rx_errors;

  /// TX-side loss %
  @ffi.Float()
  external double loss_pct;

  /// RX-side loss %
  @ffi.Float()
  external double loss_pct_rx;

  /// RX interarrival jitter (what we observe)
  @ffi.Float()
  external double jitter_ms;

  /// TX interarrival jitter (what remote reports)
  @ffi.Float()
  external double tx_jitter_ms;

  /// round-trip time ms
  @ffi.Float()
  external double rtt_ms;

  /// current adaptive buffer depth (ms)
  @ffi.Uint32()
  external int jitter_buffer_ms;

  /// packets currently held in buffer
  @ffi.Uint32()
  external int jitter_buffer_load;

  /// packets that arrived too late
  @ffi.Uint32()
  external int late_packets;

  /// packets discarded (overflow / flush)
  @ffi.Uint32()
  external int discarded_packets;

  /// current TX bitrate (kbps)
  @ffi.Uint32()
  external int bandwidth_kbps_tx;

  /// current RX bitrate (kbps)
  @ffi.Uint32()
  external int bandwidth_kbps_rx;

  /// session-average TX bitrate (kbps)
  @ffi.Uint32()
  external int avg_bandwidth_kbps_tx;

  /// session-average RX bitrate (kbps)
  @ffi.Uint32()
  external int avg_bandwidth_kbps_rx;

  /// listening quality  (1.0–4.5)
  @ffi.Float()
  external double mos_lq;

  /// conversational quality (1.0–4.5)
  @ffi.Float()
  external double mos_cq;

  @ffi.Int32()
  external int mos_method;

  /// e.g. "opus", "PCMU"
  external ffi.Pointer<ffi.Char> codec_name;

  /// RTP clock rate Hz
  @ffi.Uint32()
  external int codec_clock_rate;

  /// audio sample rate Hz
  @ffi.Uint32()
  external int codec_sample_rate;

  /// 1=mono, 2=stereo
  @ffi.Uint8()
  external int codec_channels;

  /// RTP payload type number (0-127)
  @ffi.Int()
  external int payload_type;

  /// received audio level dBov (0=max, -127=silent);
  /// NaN when unavailable
  @ffi.Float()
  external double audio_level_dbov;

  /// our SSRC
  @ffi.Uint32()
  external int ssrc_tx;

  /// remote SSRC (0 if not yet received)
  @ffi.Uint32()
  external int ssrc_rx;

  /// remote RTP address "ip:port\0"
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> remote_addr;
}

final class baresdk_ev_log_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> message;
}

final class baresdk_ev_registrar_warning_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> message;
}

/// Incoming REFER request — blind transfer or attended (has_replaces=true).
final class baresdk_ev_transfer_req_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  /// call receiving the REFER
  external baresdk_call_handle_t call;

  /// Refer-To header value
  external ffi.Pointer<ffi.Char> refer_to_uri;

  /// true = attended transfer
  @ffi.Bool()
  external bool has_replaces;
}

/// MWI NOTIFY — raw body is parsed into counters; all fields may be 0.
final class baresdk_ev_mwi_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  @ffi.Bool()
  external bool messages_waiting;

  @ffi.Uint32()
  external int new_voice;

  @ffi.Uint32()
  external int old_voice;

  @ffi.Uint32()
  external int new_urgent;

  @ffi.Uint32()
  external int old_urgent;

  /// full NOTIFY body
  external ffi.Pointer<ffi.Char> raw_body;
}

/// Incoming SIP MESSAGE (instant message).
final class baresdk_ev_message_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  external ffi.Pointer<ffi.Char> from_uri;

  external ffi.Pointer<ffi.Char> body;

  /// e.g. "text/plain"
  external ffi.Pointer<ffi.Char> content_type;
}

/// Buddy / contact presence state changed.
final class baresdk_ev_presence_state_t extends ffi.Struct {
  external baresdk_account_handle_t account;

  external ffi.Pointer<ffi.Char> target_uri;

  @ffi.Int32()
  external int status;
}

/// ── Master event union ─────────────────────────────────────────────────────
final class baresdk_event_t extends ffi.Struct {
  @ffi.Int32()
  external int type;

  external UnnamedUnion1 u;
}

final class UnnamedUnion1 extends ffi.Union {
  external baresdk_ev_log_t log;

  external baresdk_ev_reg_state_t reg;

  external baresdk_ev_incoming_call_t incoming;

  external baresdk_ev_call_state_t call_state;

  external baresdk_ev_call_dtmf_t dtmf;

  external baresdk_ev_sdp_negotiation_t sdp;

  external baresdk_ev_sip_trace_t sip_trace;

  external baresdk_ev_media_stats_t stats;

  external baresdk_ev_registrar_warning_t reg_warn;

  external baresdk_ev_transfer_req_t transfer_req;

  external baresdk_ev_mwi_t mwi;

  external baresdk_ev_message_t msg;

  external baresdk_ev_presence_state_t presence;
}

final class baresdk_config_t extends ffi.Struct {
  /// BARESDK_CONFIG_VERSION
  @ffi.Uint32()
  external int version;

  /// sizeof(baresdk_config_t) at compile time
  @ffi.Size()
  external int struct_size;

  /// ── Transport ──────────────────────────────────────────────────
  @ffi.Int32()
  external int transport;

  /// NULL = auto
  external ffi.Pointer<ffi.Char> local_ip;

  /// 0 = OS-assigned
  @ffi.Uint16()
  external int local_port;

  /// NULL = any, e.g. "wlan0"
  external ffi.Pointer<ffi.Char> bind_interface;

  @ffi.Bool()
  external bool prefer_ipv6;

  /// AOR domain, e.g. "pbx.example.com"
  external ffi.Pointer<ffi.Char> sip_domain;

  /// full URL, takes precedence
  external ffi.Pointer<ffi.Char> server_url;

  /// simple form
  external ffi.Pointer<ffi.Char> server_host;

  /// 0 = transport default
  @ffi.Uint16()
  external int server_port;

  /// NULL = direct; same URL grammar
  external ffi.Pointer<ffi.Char> outbound_proxy;

  /// ── TLS / WSS ──────────────────────────────────────────────────
  external ffi.Pointer<ffi.Char> ca_cert_path;

  external ffi.Pointer<ffi.Char> client_cert;

  external ffi.Pointer<ffi.Char> client_key;

  @ffi.Bool()
  external bool verify_server;

  /// SNI hostname — NULL derives from server_url host.
  /// Set explicitly when the reverse-proxy cert SNI differs from
  /// the SIP domain (e.g. proxy cert for "proxy.example.com" but
  /// SIP domain is "pbx.internal").
  external ffi.Pointer<ffi.Char> sni_hostname;

  /// SIP User-Agent header value
  external ffi.Pointer<ffi.Char> user_agent;

  /// NULL = auto-derived from server_url
  external ffi.Pointer<ffi.Char> ws_origin;

  /// NULL-terminated "Header: value" strings
  external ffi.Pointer<ffi.Pointer<ffi.Char>> ws_extra_headers;

  /// ── NAT ────────────────────────────────────────────────────────
  external ffi.Pointer<ffi.Char> stun_server;

  external ffi.Pointer<ffi.Char> turn_server;

  external ffi.Pointer<ffi.Char> turn_user;

  external ffi.Pointer<ffi.Char> turn_pass;

  @ffi.Bool()
  external bool ice_enabled;

  /// ── Media ──────────────────────────────────────────────────────
  @ffi.Int32()
  external int media_enc;

  /// ordered preference list
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int32> audio_codecs;

  @ffi.Int()
  external int audio_codec_count;

  /// 0 = OS default; 24 = AF31
  @ffi.Uint8()
  external int dscp_sip;

  /// 0 = OS default; 46 = EF
  @ffi.Uint8()
  external int dscp_rtp;

  /// reserved for future video support
  @ffi.Bool()
  external bool enable_video;

  /// acoustic echo cancellation
  @ffi.Bool()
  external bool aec;

  /// noise suppression
  @ffi.Bool()
  external bool ns;

  /// automatic gain control
  @ffi.Bool()
  external bool agc;

  /// minimum adaptive buffer depth; 0 = baresip default
  @ffi.Uint32()
  external int jitter_buffer_min_ms;

  /// maximum adaptive buffer depth; 0 = baresip default
  @ffi.Uint32()
  external int jitter_buffer_max_ms;

  /// seconds; default 3600
  @ffi.Uint32()
  external int reg_expires;

  /// refresh at N% of expires; default 75
  @ffi.Uint32()
  external int reg_refresh_pct;

  /// ms; 0 = transport default
  @ffi.Uint32()
  external int keepalive_interval;

  /// default 2000
  @ffi.Uint32()
  external int reg_retry_initial_ms;

  /// default 300000 (5 min)
  @ffi.Uint32()
  external int reg_retry_max_ms;

  /// multiplier; default 2.0
  @ffi.Float()
  external double reg_retry_backoff;

  /// 0 = retry forever
  @ffi.Uint32()
  external int reg_retry_max_attempts;

  /// default 500
  @ffi.Uint32()
  external int sip_t1_ms;

  /// default 4000
  @ffi.Uint32()
  external int sip_t2_ms;

  /// default 32000
  @ffi.Uint32()
  external int sip_timer_b_ms;

  /// default 32000
  @ffi.Uint32()
  external int sip_timer_f_ms;

  /// default true
  @ffi.Bool()
  external bool session_timer_enabled;

  /// default 1800
  @ffi.Uint32()
  external int session_expires_s;

  /// default 90
  @ffi.Uint32()
  external int session_min_se_s;

  /// 0 = disabled
  @ffi.Uint32()
  external int stats_interval_ms;

  @ffi.Int32()
  external int mos_method;

  /// emit BARESDK_EV_SIP_TRACE per message
  @ffi.Bool()
  external bool trace_sip;

  /// emit BARESDK_EV_SDP_NEGOTIATION
  @ffi.Bool()
  external bool trace_sdp_diff;

  /// NULL = no pcap; path = live capture
  external ffi.Pointer<ffi.Char> pcap_path;

  /// 0=err, 1=warn, 2=info, 3=debug
  @ffi.Int()
  external int log_level;

  /// required
  external baresdk_event_cb_t event_cb;

  external ffi.Pointer<ffi.Void> event_userdata;
}

/// Event callback — fired from baresdk's internal event thread.
/// Must return within 10 ms. Do not call baresdk APIs synchronously
/// from inside this callback (use a separate thread or post to your
/// own queue and return).
typedef baresdk_event_cb_t
    = ffi.Pointer<ffi.NativeFunction<baresdk_event_cb_tFunction>>;
typedef baresdk_event_cb_tFunction = ffi.Void Function(
    ffi.Pointer<baresdk_event_t> ev, ffi.Pointer<ffi.Void> userdata);
typedef Dartbaresdk_event_cb_tFunction = void Function(
    ffi.Pointer<baresdk_event_t> ev, ffi.Pointer<ffi.Void> userdata);

/// ── Account config ─────────────────────────────────────────────────────────
final class baresdk_account_config_t extends ffi.Struct {
  /// Login URI — who you are and where the server is.
  /// Accepted forms:
  /// "user@host"            →  AOR sip:user@host, server = host:default_port
  /// "user@host:port"       →  AOR sip:user@host, server = host:port
  /// "sip:user@host"        →  same as "user@host"
  /// Required.
  external ffi.Pointer<ffi.Char> uri;

  /// digest auth password — required
  external ffi.Pointer<ffi.Char> password;

  /// SIP transport protocol.  Defaults to BARESDK_TRANSPORT_UDP (0).
  /// Ignored when server_url is set (transport is derived from the URL scheme).
  @ffi.Int32()
  external int transport;

  /// NULL = host from uri
  external ffi.Pointer<ffi.Char> server_host;

  /// 0    = port from uri, or transport default
  @ffi.Uint16()
  external int server_port;

  /// Full server URL for WebSocket transports or non-standard paths.
  /// "wss://pbx.example.com:443/ws"
  /// "ws://pbx.internal:8088/"
  /// When set, overrides transport, server_host, and server_port.
  external ffi.Pointer<ffi.Char> server_url;

  /// NULL = user part of uri
  external ffi.Pointer<ffi.Char> auth_user;

  /// NULL = omit
  external ffi.Pointer<ffi.Char> display_name;

  /// BARESDK_MEDIA_ENC_NONE / SDES / DTLS_SRTP
  @ffi.Int32()
  external int media_enc;

  /// false by default
  @ffi.Bool()
  external bool ice_enabled;

  /// NULL = no STUN, e.g. "stun:stun.l.google.com:19302"
  external ffi.Pointer<ffi.Char> stun_server;

  /// NULL = no TURN, e.g. "turn:turn.example.com:3478"
  external ffi.Pointer<ffi.Char> turn_server;

  external ffi.Pointer<ffi.Char> turn_user;

  external ffi.Pointer<ffi.Char> turn_pass;

  /// NULL = auto-derived from server
  external ffi.Pointer<ffi.Char> outbound;

  /// false = skip TLS cert verification
  @ffi.Bool()
  external bool verify_tls;
}

/// ── Audio device enumeration ───────────────────────────────────────────────
final class baresdk_audio_device_t extends ffi.Struct {
  /// device name passed to set_input/output_device
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;

  /// human-readable label (may be empty)
  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> description;

  /// true for the platform default device
  @ffi.Bool()
  external bool is_default;
}

/// Media tap callback — fired from the audio thread on each audio frame.
/// Must be non-blocking. Copy PCM data if you need it beyond the callback.
typedef baresdk_media_tap_cb_t
    = ffi.Pointer<ffi.NativeFunction<baresdk_media_tap_cb_tFunction>>;
typedef baresdk_media_tap_cb_tFunction = ffi.Void Function(
    baresdk_call_handle_t call,
    ffi.Int32 direction,
    ffi.Pointer<ffi.Int16> pcm,
    ffi.Size samples,
    ffi.Uint32 sample_rate,
    ffi.Uint8 channels,
    ffi.Uint64 timestamp_us,
    ffi.Pointer<ffi.Void> userdata);
typedef Dartbaresdk_media_tap_cb_tFunction = void Function(
    baresdk_call_handle_t call,
    int direction,
    ffi.Pointer<ffi.Int16> pcm,
    int samples,
    int sample_rate,
    int channels,
    int timestamp_us,
    ffi.Pointer<ffi.Void> userdata);

const int BARESDK_VERSION_MAJOR = 1;

const int BARESDK_VERSION_MINOR = 0;

const int BARESDK_VERSION_PATCH = 0;

const int BARESDK_CONFIG_VERSION = 1;
