/**
 * @file ca_ios.c  iOS CA trust store
 *
 * iOS is the one platform that will not hand us its trust store:
 *
 *   - macOS has SecTrustCopyAnchorCertificates(); on iOS that API does not
 *     exist, and no other public API enumerates the system anchors.
 *   - Android keeps its roots as files under /system/etc/security/cacerts,
 *     which platform/android/ca_android.c concatenates.  iOS ships no
 *     equivalent directory, and the app sandbox could not read one anyway.
 *
 * We link our own OpenSSL on iOS (scripts/build-ios.sh builds it from source
 * because the system has no linkable libssl), and libre never calls
 * SSL_CTX_set_default_verify_paths().  So without this file the X509_STORE
 * behind uag_tls() is empty and *every* TLS/WSS registration fails the
 * handshake with "unable to get local issuer certificate" — reported up the
 * stack as the generic "Register: Protocol error [100]".
 *
 * The fix is the same one curl, gRPC and every other OpenSSL-on-iOS consumer
 * uses: carry the Mozilla root bundle ourselves (ca_roots.c, regenerated by
 * scripts/gen-ca-roots.sh) and drop it in the app's own container for OpenSSL
 * to read as a CAfile.
 *
 * Consequence worth knowing: this trusts the roots we shipped, not the ones
 * the device trusts.  A CA that iOS distrusts after our bundle was cut still
 * verifies here, and an enterprise/MDM root the device was given does not —
 * a deployment behind a corporate TLS proxy has to pass its own bundle as
 * echosdk_config_t.ca_cert_path, which takes priority over this.
 */

#include <stdio.h>
#include <stddef.h>
#include <sys/stat.h>
#include <re.h>
#include "../../src/echosdk_internal.h"

/* platform/ios/ca_roots.c (generated) */
extern const char   bsdk_ca_roots_pem[];
extern const size_t bsdk_ca_roots_pem_len;

const char *bsdk_platform_ca_bundle(const char *dir)
{
	static char path[700];
	struct stat st;
	FILE *out;
	size_t n;

	if (!dir || !*dir)
		return NULL;

	(void)re_snprintf(path, sizeof(path), "%s/ca-bundle.pem", dir);

	/* Written once per container, not once per init: the bundle only
	 * changes when the app itself is replaced, and a matching size means
	 * this build already wrote it.  Size is enough — the contents are a
	 * compile-time constant, so they cannot drift at a fixed length. */
	if (stat(path, &st) == 0 &&
	    (size_t)st.st_size == bsdk_ca_roots_pem_len)
		return path;

	out = fopen(path, "w");
	if (!out) {
		warning("EchoSDK: cannot write CA bundle to %s — TLS server "
		        "verification will fail unless ca_cert_path is set\n",
		        path);
		return NULL;
	}

	n = fwrite(bsdk_ca_roots_pem, 1, bsdk_ca_roots_pem_len, out);
	if (fclose(out) != 0 || n != bsdk_ca_roots_pem_len) {
		warning("EchoSDK: short write of CA bundle to %s (%zu/%zu) — "
		        "TLS server verification will fail unless ca_cert_path "
		        "is set\n", path, n, bsdk_ca_roots_pem_len);
		(void)remove(path);
		return NULL;
	}

	return path;
}
