#!/usr/bin/env bash
# Regenerate platform/ios/ca_roots.c from the Mozilla CA bundle.
#
# iOS is the one platform whose system trust store cannot be read: unlike
# macOS it has no SecTrustCopyAnchorCertificates, and unlike Android there is
# no directory of PEMs on disk.  The bundled OpenSSL therefore starts with an
# empty X509_STORE and every server certificate fails verification with
# "unable to get local issuer certificate".  The roots have to ship with us.
#
# Re-run when the bundle goes stale (Mozilla drops or adds a root); commit the
# regenerated ca_roots.c.  The date the bundle was cut stays in its header
# comment, which OpenSSL skips when parsing.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/platform/ios/ca_roots.c"
URL="${1:-https://curl.se/ca/cacert.pem}"

PEM="$(mktemp)"
trap 'rm -f "${PEM}"' EXIT

echo "==> fetching ${URL}"
curl -sSfL -o "${PEM}" "${URL}"

count="$(grep -c 'BEGIN CERTIFICATE' "${PEM}")"
if [[ "${count}" -lt 50 ]]; then
  echo "ERROR: only ${count} certificates in the bundle — refusing to write" >&2
  exit 1
fi
echo "==> ${count} roots"

{
  cat <<'HDR'
/**
 * @file ca_roots.c  Mozilla CA root bundle, embedded (iOS)
 *
 * GENERATED by scripts/gen-ca-roots.sh — do not edit by hand.
 *
 * See ca_ios.c for why iOS needs the roots compiled in rather than read from
 * the system trust store.
 */

#include <stddef.h>

/* Declared extern in ca_ios.c, the only consumer. */

const char vox_ca_roots_pem[] =
HDR
  # One C string literal per line; adjacent literals concatenate into one
  # array initialiser.  Escaping is defensive — PEM is base64 plus ASCII
  # subject names, neither of which contains a quote or a backslash.
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/\t"/' -e 's/$/\\n"/' "${PEM}"
  echo ";"
  echo ""
  echo "const size_t vox_ca_roots_pem_len = sizeof(vox_ca_roots_pem) - 1;"
} > "${OUT}"

echo "==> wrote ${OUT} ($(wc -c < "${OUT}") bytes)"
