//! Raw FFI bindings for baresdk, generated by bindgen.
//!
//! Most users should depend on the `baresdk` crate (safe wrapper) instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
